spring:
    datasource: #数据源
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/business?useSSL=false&serverTimezone=GMT&nullCatalogMeansCurrent = true
        username: root
        password: 123
        max-active: 20
        max-wait: 6000
        min-idle: 1
        test-on-borrow: true
        test-on-return: true
mybatis:
    mapper-locations: classpath*:com/overload/mapper/*Mapper.xml
    config-location: classpath:mybatis-config.xml

